[tool.poetry]
name = "danio"
version = "0.4.4.0"
description = "ORM for asyncio world by dataclass"
authors = ["strongbugman <strongbugman@gmail.com>"]
license = "BSD 3-Clause"
readme = "README.md"
classifiers=[
    "Environment :: Console",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "danio" },
]

[tool.poetry.dependencies]
python = "^3.7"
databases = "^0.4.3"
cached-property = "^1.5.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pytest-asyncio = ">=0.8.0"
pytest-cov = ">=2.5.1"
aiomysql = "^0.0.21"
mypy = "^0.910"
flake8 = "^3.9.2"
isort = "^5.9.2"
black = "^21.8b0"
types-PyMySQL = "^1.0.2"
mkdocs-material = "^8.2.3"
codecov = "^2.1.12"
aiosqlite = "^0.17.0"
asyncpg = "^0.25.0"
aiopg = "^1.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
